-- Life Tracker 1.3.0 protected entitlements, atomic quotas, flight matching,
-- demo sessions, invite redemption and cached AI content.

create extension if not exists pgcrypto;

alter table public.records
  add column if not exists actual_match_status text not null default 'never',
  add column if not exists actual_info jsonb,
  add column if not exists actual_info_matched boolean not null default false,
  add column if not exists actual_matched_at timestamptz,
  add column if not exists actual_match_provider text,
  add column if not exists actual_match_request_id uuid;

alter table public.records drop constraint if exists records_actual_match_status_check;
alter table public.records add constraint records_actual_match_status_check
  check (actual_match_status in ('never', 'eligible', 'matching', 'matched', 'not_found', 'failed'));

alter table public.records drop constraint if exists records_actual_info_object_check;
alter table public.records add constraint records_actual_info_object_check
  check (actual_info is null or jsonb_typeof(actual_info) = 'object');

create unique index if not exists records_actual_match_request_idx
  on public.records(actual_match_request_id) where actual_match_request_id is not null;

create table if not exists public.api_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  tier text not null default 'standard' check (tier in ('standard', 'friend', 'owner')),
  source text not null default 'default' check (source in ('default', 'invite', 'owner_bootstrap', 'admin')),
  granted_at timestamptz not null default now(),
  revoked_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.invite_codes (
  id uuid primary key default gen_random_uuid(),
  code_hash text not null unique check (char_length(code_hash) = 64),
  label text not null default 'friends',
  active boolean not null default true,
  max_redemptions integer,
  redeemed_count integer not null default 0 check (redeemed_count >= 0),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invite_redemptions (
  id uuid primary key default gen_random_uuid(),
  invite_code_id uuid not null references public.invite_codes(id) on delete restrict,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  redeemed_at timestamptz not null default now()
);

create table if not exists public.invite_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  succeeded boolean not null default false,
  attempted_at timestamptz not null default now()
);

create index if not exists invite_attempts_user_time_idx on public.invite_attempts(user_id, attempted_at desc);

create table if not exists public.demo_sessions (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique check (char_length(token_hash) = 64),
  device_hash text not null check (char_length(device_hash) between 32 and 128),
  expires_at timestamptz not null,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists demo_sessions_device_idx on public.demo_sessions(device_hash, expires_at desc);

create table if not exists public.api_quota_policies (
  policy_key text primary key,
  service text not null check (service in ('aviation', 'deepseek')),
  quota_group text not null,
  tier text not null check (tier in ('demo', 'standard', 'friend', 'owner', 'shared')),
  period_type text not null check (period_type in ('day', 'month', 'rolling')),
  limit_value integer not null check (limit_value > 0),
  soft_limit boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.api_quota_buckets (
  bucket_key text primary key,
  service text not null check (service in ('aviation', 'deepseek')),
  quota_group text not null,
  period_start timestamptz not null,
  period_end timestamptz not null,
  limit_value integer not null check (limit_value > 0),
  used_value integer not null default 0 check (used_value >= 0),
  updated_at timestamptz not null default now()
);

create index if not exists api_quota_buckets_period_idx on public.api_quota_buckets(service, period_end);

create table if not exists public.api_usage_events (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null unique,
  user_id uuid references auth.users(id) on delete cascade,
  demo_session_id uuid references public.demo_sessions(id) on delete cascade,
  service text not null check (service in ('aviation', 'deepseek')),
  feature text not null,
  quota_group text not null,
  tier text not null check (tier in ('demo', 'standard', 'friend', 'owner')),
  status text not null default 'reserved' check (status in ('reserved', 'completed', 'upstream_error', 'not_found', 'failed')),
  counted boolean not null default true,
  response_meta jsonb,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint api_usage_principal_check check ((user_id is null) <> (demo_session_id is null))
);

create index if not exists api_usage_user_time_idx on public.api_usage_events(user_id, created_at desc) where user_id is not null;
create index if not exists api_usage_demo_time_idx on public.api_usage_events(demo_session_id, created_at desc) where demo_session_id is not null;
create index if not exists api_usage_service_month_idx on public.api_usage_events(service, created_at desc) where counted;

create table if not exists public.api_cooldowns (
  principal_key text primary key,
  reason text not null,
  until_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.flight_match_previews (
  request_id uuid primary key,
  record_id uuid not null references public.records(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  actual_info jsonb not null check (jsonb_typeof(actual_info) = 'object'),
  expires_at timestamptz not null default (now() + interval '30 minutes'),
  created_at timestamptz not null default now(),
  unique (record_id, request_id)
);

create table if not exists public.trip_recaps (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  trip_id uuid not null references public.trips(id) on delete cascade,
  content text not null,
  source_snapshot_hash text not null,
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, trip_id)
);

create table if not exists public.daily_summaries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  summary_date date not null,
  content text not null,
  generated_at timestamptz not null default now(),
  unique (user_id, summary_date)
);

insert into public.api_quota_policies (policy_key, service, quota_group, tier, period_type, limit_value, soft_limit)
values
  ('aviation_standard_daily', 'aviation', 'flight', 'standard', 'day', 2, false),
  ('aviation_shared_monthly', 'aviation', 'flight', 'shared', 'month', 80, false),
  ('aviation_owner_monthly', 'aviation', 'flight', 'owner', 'month', 20, false),
  ('ai_light_demo_daily', 'deepseek', 'light', 'demo', 'day', 2, false),
  ('ai_light_standard_daily', 'deepseek', 'light', 'standard', 'day', 15, false),
  ('ai_light_owner_daily', 'deepseek', 'light', 'owner', 'day', 200, true),
  ('ai_light_shared_monthly', 'deepseek', 'light', 'shared', 'month', 10000, false),
  ('ai_recap_standard_monthly', 'deepseek', 'recap', 'standard', 'month', 3, false),
  ('ai_recap_friend_monthly', 'deepseek', 'recap', 'friend', 'month', 10, false),
  ('ai_recap_owner_monthly', 'deepseek', 'recap', 'owner', 'month', 50, true),
  ('ai_summary_standard_daily', 'deepseek', 'summary', 'standard', 'day', 1, false)
on conflict (policy_key) do update set
  service = excluded.service,
  quota_group = excluded.quota_group,
  tier = excluded.tier,
  period_type = excluded.period_type,
  limit_value = excluded.limit_value,
  soft_limit = excluded.soft_limit,
  updated_at = now();

-- Store only the hash. The clear invite code is distributed privately and can
-- be replaced by inserting a new hash and deactivating this row.
insert into public.invite_codes (code_hash, label)
values ('7b62cfc9ba55cccef3f00dcfa325abb68340a943b34e74089e1d795f68a2da83', 'v1.3 friends')
on conflict (code_hash) do nothing;

-- Resolve the existing owner account once, then persist the Auth UUID. No owner
-- email or invite rule is exposed to the client application.
insert into public.api_entitlements (user_id, tier, source)
select id, 'owner', 'owner_bootstrap'
from auth.users
where encode(extensions.digest(lower(email), 'sha256'::text), 'hex') = '65a64dff94079533ab3aeecd6c5068f193532cf6f9c6c853bc76a0cdfef9df0c'
on conflict (user_id) do update set tier = 'owner', source = 'owner_bootstrap', revoked_at = null, updated_at = now();

create or replace function public.redeem_friend_invite(p_user_id uuid, p_code_hash text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  code_row public.invite_codes%rowtype;
  current_tier text;
begin
  if p_user_id is null or p_code_hash !~ '^[0-9a-f]{64}$' then
    return jsonb_build_object('ok', false, 'code', 'INVALID_INVITE');
  end if;

  if (select count(*) from public.invite_attempts where user_id = p_user_id and attempted_at > now() - interval '1 hour' and not succeeded) >= 5 then
    return jsonb_build_object('ok', false, 'code', 'TOO_MANY_ATTEMPTS');
  end if;

  select tier into current_tier from public.api_entitlements where user_id = p_user_id and revoked_at is null;
  if current_tier = 'owner' then
    return jsonb_build_object('ok', true, 'tier', 'owner');
  end if;
  if current_tier = 'friend' then
    return jsonb_build_object('ok', true, 'tier', 'friend');
  end if;

  select * into code_row from public.invite_codes
  where code_hash = p_code_hash and active and (expires_at is null or expires_at > now())
    and (max_redemptions is null or redeemed_count < max_redemptions)
  for update;

  if code_row.id is null then
    insert into public.invite_attempts(user_id, succeeded) values (p_user_id, false);
    return jsonb_build_object('ok', false, 'code', 'INVALID_INVITE');
  end if;

  insert into public.invite_redemptions(invite_code_id, user_id)
  values (code_row.id, p_user_id)
  on conflict (user_id) do nothing;
  update public.invite_codes set redeemed_count = redeemed_count + 1, updated_at = now() where id = code_row.id;
  insert into public.api_entitlements(user_id, tier, source)
  values (p_user_id, 'friend', 'invite')
  on conflict (user_id) do update set tier = case when api_entitlements.tier = 'owner' then 'owner' else 'friend' end,
    source = case when api_entitlements.tier = 'owner' then api_entitlements.source else 'invite' end,
    revoked_at = null,
    updated_at = now();
  insert into public.invite_attempts(user_id, succeeded) values (p_user_id, true);
  return jsonb_build_object('ok', true, 'tier', 'friend');
end;
$$;

create or replace function public.consume_api_quota(
  p_user_id uuid,
  p_demo_session_id uuid,
  p_feature text,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tier text := 'standard';
  v_service text;
  v_group text;
  v_principal text;
  v_day_start timestamptz := date_trunc('day', now() at time zone 'Asia/Shanghai') at time zone 'Asia/Shanghai';
  v_day_end timestamptz;
  v_month_start timestamptz := date_trunc('month', now() at time zone 'Asia/Shanghai') at time zone 'Asia/Shanghai';
  v_month_end timestamptz;
  v_keys text[] := array[]::text[];
  v_limits integer[] := array[]::integer[];
  v_groups text[] := array[]::text[];
  v_starts timestamptz[] := array[]::timestamptz[];
  v_ends timestamptz[] := array[]::timestamptz[];
  v_key text;
  v_used integer;
  v_limit integer;
  v_index integer;
  v_cooldown timestamptz;
begin
  v_day_end := v_day_start + interval '1 day';
  v_month_end := v_month_start + interval '1 month';

  if p_request_id is null or p_feature not in ('flight_actual_match', 'route', 'expense_parse', 'note_polish', 'trip_recap', 'daily_summary') then
    return jsonb_build_object('allowed', false, 'code', 'INVALID_REQUEST');
  end if;
  if (p_user_id is null) = (p_demo_session_id is null) then
    return jsonb_build_object('allowed', false, 'code', 'INVALID_PRINCIPAL');
  end if;

  if exists (select 1 from public.api_usage_events where request_id = p_request_id) then
    return jsonb_build_object('allowed', false, 'code', 'DUPLICATE_REQUEST', 'duplicate', true);
  end if;

  if p_demo_session_id is not null then
    if not exists (select 1 from public.demo_sessions where id = p_demo_session_id and expires_at > now()) then
      return jsonb_build_object('allowed', false, 'code', 'DEMO_SESSION_EXPIRED');
    end if;
    v_tier := 'demo';
    v_principal := 'demo:' || p_demo_session_id::text;
  else
    select tier into v_tier from public.api_entitlements where user_id = p_user_id and revoked_at is null;
    v_tier := coalesce(v_tier, 'standard');
    v_principal := 'user:' || p_user_id::text;
  end if;

  v_service := case when p_feature = 'flight_actual_match' then 'aviation' else 'deepseek' end;
  v_group := case when p_feature = 'flight_actual_match' then 'flight'
                  when p_feature in ('route', 'expense_parse', 'note_polish') then 'light'
                  when p_feature = 'trip_recap' then 'recap' else 'summary' end;

  if v_tier = 'demo' and p_feature in ('flight_actual_match', 'trip_recap', 'daily_summary') then
    return jsonb_build_object('allowed', false, 'code', 'DEMO_MOCK_ONLY', 'tier', v_tier);
  end if;

  if v_service = 'deepseek' and v_tier <> 'owner' then
    select until_at into v_cooldown from public.api_cooldowns where principal_key = v_principal and until_at > now();
    if v_cooldown is not null then
      return jsonb_build_object('allowed', false, 'code', 'COOLDOWN', 'tier', v_tier, 'retry_at', v_cooldown);
    end if;
    if (select count(*) from public.api_usage_events where
        ((p_user_id is not null and user_id = p_user_id) or (p_demo_session_id is not null and demo_session_id = p_demo_session_id))
        and service = 'deepseek' and counted and created_at > now() - interval '60 seconds') >= 10 then
      insert into public.api_cooldowns(principal_key, reason, until_at)
      values (v_principal, 'burst_limit', now() + interval '5 minutes')
      on conflict (principal_key) do update set until_at = excluded.until_at, reason = excluded.reason, updated_at = now();
      return jsonb_build_object('allowed', false, 'code', 'COOLDOWN', 'tier', v_tier, 'retry_at', now() + interval '5 minutes');
    end if;
  end if;

  if p_feature = 'flight_actual_match' then
    if v_tier = 'demo' then
      return jsonb_build_object('allowed', false, 'code', 'DEMO_MOCK_ONLY', 'tier', v_tier);
    elsif v_tier = 'owner' then
      v_keys := array['aviation:owner:' || to_char(v_month_start at time zone 'Asia/Shanghai', 'YYYY-MM')];
      v_limits := array[20]; v_groups := array['flight']; v_starts := array[v_month_start]; v_ends := array[v_month_end];
    else
      v_keys := array['aviation:shared:' || to_char(v_month_start at time zone 'Asia/Shanghai', 'YYYY-MM')];
      v_limits := array[80]; v_groups := array['flight']; v_starts := array[v_month_start]; v_ends := array[v_month_end];
      if v_tier = 'standard' then
        v_keys := array_append(v_keys, 'aviation:standard:' || p_user_id::text || ':' || to_char(v_day_start at time zone 'Asia/Shanghai', 'YYYY-MM-DD'));
        v_limits := array_append(v_limits, 2); v_groups := array_append(v_groups, 'flight'); v_starts := array_append(v_starts, v_day_start); v_ends := array_append(v_ends, v_day_end);
      end if;
    end if;
  elsif v_group = 'light' then
    if v_tier = 'owner' then
      v_keys := array['deepseek:light:owner:' || p_user_id::text || ':' || to_char(v_day_start at time zone 'Asia/Shanghai', 'YYYY-MM-DD')];
      v_limits := array[200]; v_groups := array['light']; v_starts := array[v_day_start]; v_ends := array[v_day_end];
    else
      v_keys := array['deepseek:light:shared:' || to_char(v_month_start at time zone 'Asia/Shanghai', 'YYYY-MM')];
      v_limits := array[10000]; v_groups := array['light']; v_starts := array[v_month_start]; v_ends := array[v_month_end];
      if v_tier = 'standard' then
        v_keys := array_append(v_keys, 'deepseek:light:standard:' || p_user_id::text || ':' || to_char(v_day_start at time zone 'Asia/Shanghai', 'YYYY-MM-DD'));
        v_limits := array_append(v_limits, 15); v_groups := array_append(v_groups, 'light'); v_starts := array_append(v_starts, v_day_start); v_ends := array_append(v_ends, v_day_end);
      elsif v_tier = 'demo' then
        v_keys := array_append(v_keys, 'deepseek:light:demo:' || p_demo_session_id::text || ':' || to_char(v_day_start at time zone 'Asia/Shanghai', 'YYYY-MM-DD'));
        v_limits := array_append(v_limits, 2); v_groups := array_append(v_groups, 'light'); v_starts := array_append(v_starts, v_day_start); v_ends := array_append(v_ends, v_day_end);
        v_keys := array_append(v_keys, 'deepseek:light:demo-global:' || to_char(v_day_start at time zone 'Asia/Shanghai', 'YYYY-MM-DD'));
        v_limits := array_append(v_limits, 100); v_groups := array_append(v_groups, 'light'); v_starts := array_append(v_starts, v_day_start); v_ends := array_append(v_ends, v_day_end);
      end if;
    end if;
  elsif p_feature = 'trip_recap' then
    if v_tier = 'demo' then return jsonb_build_object('allowed', false, 'code', 'DEMO_MOCK_ONLY', 'tier', v_tier); end if;
    v_limit := case v_tier when 'owner' then 50 when 'friend' then 10 else 3 end;
    v_keys := array['deepseek:recap:' || v_tier || ':' || p_user_id::text || ':' || to_char(v_month_start at time zone 'Asia/Shanghai', 'YYYY-MM')];
    v_limits := array[v_limit]; v_groups := array['recap']; v_starts := array[v_month_start]; v_ends := array[v_month_end];
  elsif p_feature = 'daily_summary' and v_tier = 'standard' then
    v_keys := array['deepseek:summary:standard:' || p_user_id::text || ':' || to_char(v_day_start at time zone 'Asia/Shanghai', 'YYYY-MM-DD')];
    v_limits := array[1]; v_groups := array['summary']; v_starts := array[v_day_start]; v_ends := array[v_day_end];
  end if;

  -- One transaction-level advisory lock protects all bucket checks and updates.
  perform pg_advisory_xact_lock(hashtextextended('life-tracker-api-quota', 0));
  if coalesce(array_length(v_keys, 1), 0) > 0 then
    for v_index in 1..array_length(v_keys, 1) loop
      v_key := v_keys[v_index];
      insert into public.api_quota_buckets(bucket_key, service, quota_group, period_start, period_end, limit_value)
      values (v_key, v_service, v_groups[v_index], v_starts[v_index], v_ends[v_index], v_limits[v_index])
      on conflict (bucket_key) do update set limit_value = excluded.limit_value, period_end = excluded.period_end, updated_at = now();
      select used_value, limit_value into v_used, v_limit from public.api_quota_buckets where bucket_key = v_key for update;
      if v_used >= v_limit then
        return jsonb_build_object('allowed', false,
          'code', case when v_service = 'aviation' then 'AVIATION_QUOTA_EXCEEDED'
                       when v_group = 'light' and v_key like '%:shared:%' then 'AI_MONTHLY_QUOTA_EXCEEDED'
                       else 'AI_QUOTA_EXCEEDED' end,
          'tier', v_tier, 'reset_at', v_ends[v_index]);
      end if;
    end loop;
    for v_index in 1..array_length(v_keys, 1) loop
      update public.api_quota_buckets set used_value = used_value + 1, updated_at = now() where bucket_key = v_keys[v_index];
    end loop;
  end if;

  insert into public.api_usage_events(request_id, user_id, demo_session_id, service, feature, quota_group, tier)
  values (p_request_id, p_user_id, p_demo_session_id, v_service, p_feature, v_group, v_tier);
  return jsonb_build_object('allowed', true, 'tier', v_tier, 'service', v_service, 'quota_group', v_group);
exception when unique_violation then
  return jsonb_build_object('allowed', false, 'code', 'DUPLICATE_REQUEST', 'duplicate', true);
end;
$$;

create or replace function public.complete_api_usage(p_request_id uuid, p_status text, p_response_meta jsonb default null)
returns void
language sql
security definer
set search_path = public
as $$
  update public.api_usage_events
  set status = case when p_status in ('completed', 'upstream_error', 'not_found', 'failed') then p_status else 'failed' end,
      response_meta = p_response_meta,
      completed_at = now()
  where request_id = p_request_id;
$$;

create or replace function public.claim_flight_match(p_user_id uuid, p_record_id uuid, p_request_id uuid, p_rematch boolean default false)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  row_record public.records%rowtype;
begin
  select * into row_record from public.records where id = p_record_id and user_id = p_user_id for update;
  if row_record.id is null or row_record.transport_type <> 'flight' then
    return jsonb_build_object('ok', false, 'code', 'RECORD_NOT_FOUND');
  end if;
  if row_record.actual_match_status = 'matched' and not p_rematch then
    return jsonb_build_object('ok', true, 'cached', true, 'actual_info', row_record.actual_info, 'matched_at', row_record.actual_matched_at);
  end if;
  if row_record.actual_match_status = 'matching' and row_record.updated_at > now() - interval '2 minutes' then
    return jsonb_build_object('ok', false, 'code', 'MATCH_IN_PROGRESS');
  end if;
  update public.records set actual_match_status = 'matching', actual_match_request_id = p_request_id, updated_at = now() where id = p_record_id;
  return jsonb_build_object('ok', true, 'cached', false, 'record', to_jsonb(row_record));
end;
$$;

create or replace function public.finish_flight_match(
  p_user_id uuid,
  p_record_id uuid,
  p_request_id uuid,
  p_status text,
  p_actual_info jsonb default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_row public.records%rowtype;
begin
  if p_status not in ('matched', 'not_found', 'failed') then raise exception 'invalid flight match status'; end if;
  update public.records
  set actual_match_status = p_status,
      actual_info = case when p_status = 'matched' then p_actual_info else actual_info end,
      actual_info_matched = (p_status = 'matched'),
      actual_matched_at = case when p_status = 'matched' then now() else actual_matched_at end,
      actual_match_provider = case when p_status = 'matched' then 'aviationstack' else actual_match_provider end,
      updated_at = now()
  where id = p_record_id and user_id = p_user_id and actual_match_request_id = p_request_id
  returning * into updated_row;
  return case when updated_row.id is null then jsonb_build_object('ok', false) else jsonb_build_object('ok', true, 'record', to_jsonb(updated_row)) end;
end;
$$;

alter table public.api_entitlements enable row level security;
alter table public.invite_codes enable row level security;
alter table public.invite_redemptions enable row level security;
alter table public.invite_attempts enable row level security;
alter table public.demo_sessions enable row level security;
alter table public.api_quota_policies enable row level security;
alter table public.api_quota_buckets enable row level security;
alter table public.api_usage_events enable row level security;
alter table public.api_cooldowns enable row level security;
alter table public.flight_match_previews enable row level security;
alter table public.trip_recaps enable row level security;
alter table public.daily_summaries enable row level security;

drop policy if exists trip_recaps_select_own on public.trip_recaps;
create policy trip_recaps_select_own on public.trip_recaps for select to authenticated using (auth.uid() = user_id);
drop policy if exists daily_summaries_select_own on public.daily_summaries;
create policy daily_summaries_select_own on public.daily_summaries for select to authenticated using (auth.uid() = user_id);

revoke all on public.api_entitlements, public.invite_codes, public.invite_redemptions, public.invite_attempts,
  public.demo_sessions, public.api_quota_policies, public.api_quota_buckets, public.api_usage_events,
  public.api_cooldowns, public.flight_match_previews, public.trip_recaps, public.daily_summaries from anon, authenticated;
grant select on public.trip_recaps, public.daily_summaries to authenticated;

revoke all on function public.redeem_friend_invite(uuid, text) from public, anon, authenticated;
revoke all on function public.consume_api_quota(uuid, uuid, text, uuid) from public, anon, authenticated;
revoke all on function public.complete_api_usage(uuid, text, jsonb) from public, anon, authenticated;
revoke all on function public.claim_flight_match(uuid, uuid, uuid, boolean) from public, anon, authenticated;
revoke all on function public.finish_flight_match(uuid, uuid, uuid, text, jsonb) from public, anon, authenticated;
grant execute on function public.redeem_friend_invite(uuid, text) to service_role;
grant execute on function public.consume_api_quota(uuid, uuid, text, uuid) to service_role;
grant execute on function public.complete_api_usage(uuid, text, jsonb) to service_role;
grant execute on function public.claim_flight_match(uuid, uuid, uuid, boolean) to service_role;
grant execute on function public.finish_flight_match(uuid, uuid, uuid, text, jsonb) to service_role;

insert into public.changelogs (version, summary, created_at)
values (
  '1.3.0',
  array[
    '新增 Standard、Friend、Owner 与本地演示四种使用模式。邮箱账号可以在设置中兑换朋友邀请码；Owner 由服务端 Auth UUID 独立识别。设置页会展示智能服务权限、当日与当月额度以及冷却状态。',
    '航班规划改为手动填写计划信息；只有在计划到达时间结束约 60 分钟后至 48 小时内，才会出现“匹配实际飞行信息”。系统按到达机场 IANA 时区换算 UTC，严格核对航班号、出发日期和起降机场，先预览计划与实际差异，确认后再保存；匹配结果会缓存且不会在打开页面时自动查询。',
    '新增常用机场离线智能补全，可使用中文、英文、城市、IATA 代码、拼音或常见别名搜索，并自动填充标准机场名、代码和当地时区。',
    '新增 AI 轻量助手：公共交通路线查询、自然语言记账解析与随记润色共用每日额度。所有结果均需预览确认，不会自动写入记录。',
    '新增旅行回顾与消费洞察、今日计划摘要。旅行回顾先在服务端聚合统计并抽样少量随记，避免把全部原始记录发送给模型；生成结果与每日摘要都会缓存，重新生成时会明确提示再次消耗额度。',
    '新增可重置的演示模式：记录、编辑和规划数据只保存在当前设备；航班使用模拟数据完整展示匹配流程，AI 每台设备每天可真实体验 2 次。演示模式不会接触真实用户数据，也不支持图片上传。',
    '行程计划统一按时间先后排列，拖动跨日会更新日期；同一日始终以时间为主排序。行程列表按进行中、未来、过去分组排序，行程与已有日程均可再次编辑，缩短日期时会明确提示超出范围的计划。',
    '智能服务新增服务端原子配额、共享额度池、频率保护、邀请码防暴力尝试、请求幂等和航班并发锁；普通记录、编辑和规划不受智能额度影响。',
    '优化移动端安全区域、表单选填标识与使用说明。建议优先使用简洁文字保存日常内容，以便后续搜索、统计与回顾。'
  ],
  now()
)
on conflict (version) do update set summary = excluded.summary, created_at = excluded.created_at;

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id, display_name, avatar_color, has_seen_onboarding, last_seen_version)
  values (
    new.id,
    left(coalesce(nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''), nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''), nullif(split_part(new.email, '@', 1), ''), 'Life Tracker 用户'), 40),
    '#0A84FF', false, '1.3.0'
  ) on conflict (user_id) do nothing;
  insert into public.api_entitlements(user_id, tier, source)
  values (new.id, 'standard', 'default') on conflict (user_id) do nothing;
  return new;
end;
$$;
